# Generated by Django 5.2.1 on 2026-05-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
