# Generated by Django 5.2.1 on 2026-06-12 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroclimatico',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='registroclimatico',
            unique_together={('estacion', 'fecha')},
        ),
    ]
