# Generated by Django 5.2.1 on 2026-06-12 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0002_alter_registroclimatico_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registroclimatico',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='estacion',
            name='activa',
        ),
        migrations.AlterField(
            model_name='estacion',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='registroclimatico',
            name='estacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clima.estacion'),
        ),
        migrations.AlterField(
            model_name='registroclimatico',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.RemoveField(
            model_name='registroclimatico',
            name='calidad',
        ),
        migrations.RemoveField(
            model_name='registroclimatico',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='registroclimatico',
            name='humedad',
        ),
        migrations.RemoveField(
            model_name='registroclimatico',
            name='presion',
        ),
    ]
