# Generated by Django 5.2.1 on 2026-06-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0003_alter_registroclimatico_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='doi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
